### ISSUE TITLE
Error: only named arguments may follow *expression

### ISSUE THREAD

**Issue by Rajat700** [dvgodoy/handyspark#19]
Hi

I installed handyspark on Google Dataproc cluster but I am unable to import it.

When I import it using from handyspark import * it gives me an error only named arguments may follow an * expression.

Can anyone please guide me on why this is happening.

**Comment by dvgodoy** [comment]
Hi @Rajat700 ,

Are you using Python 2? This error has been reported in the past for a Python 2 environment - which is not supported.
If that's the case, the error should go away as soon as you upgrade the environment to Python 3.

Best
